# Generated by Django 2.2.5 on 2019-09-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=15)),
                ('matches', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
            ],
        ),
    ]
